### ISSUE TITLE
无法生成证书

### ISSUE THREAD

**Issue by scymen** [quericy/one-key-ikev2-vpn#1]
VPS OS 为 debian, 想到 ubuntu 也是debian系列的，于是我修改了检测系统的函数，其他的动，应该不是问题，但是有如下错误

ca.pem [not found]
auto create ca.pem ...
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
ca.cert.pem [not found]
auto create ca.cert.pem ...
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
/usr/sbin/ipsec: unknown IPsec command `pki' (`ipsec --help' for list)
configure the pkcs12 cert password(Can be empty):
unable to load private key
19241:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:650:Expecting: ANY PRIVATE KEY
####################################
Press any key to install ikev2 VPN cert
net.ipv4.ip_forward = 1
/usr/sbin/ipsec: unknown IPsec command `start' (`ipsec --help' for list)

 [Install Successful]
 There is the default login info of your VPN
 UserName: myUserName
 PassWord: myUserPass
 PSK: myPSKkey
 you can change UserName and PassWord in /usr/local/etc/ipsec.secrets
 you must copy the cert  /root/my_key/ca.cert.pem  to the client and install it.

查看文件夹 my_key里的所有文件都是空的0字节。

**Comment by quericy** [comment]
生成证书所用的ipsec pki指令报错了。。。
可能你的strongswan安装有问题，而且这个脚本没有在debian下测试的
你可以参考或者使用这个脚本：https://github.com/magic282/One-Key-L2TP-IKEV2-Setup

**Comment by scymen** [comment]
把系统改为 centOS 6 后，说证书找不到，不知道哪里不对

make[2]: Leaving directory `/root/one-key-ikev2-vpn/strongswan-5.3.2'
make[1]: Leaving directory `/root/one-key-ikev2-vpn/strongswan-5.3.2'
ca.pem [not found]
auto create ca.pem ...
ca.cert.pem [not found]
auto create ca.cert.pem ...
configure the pkcs12 cert password(Can be empty):
Enter Export Password:
Verifying - Enter Export Password:
####################################
Press any key to install ikev2 VPN cert
net.ipv4.ip_forward = 1
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
Starting strongSwan 5.3.2 IPsec [starter]...
no netkey IPsec stack detected
no KLIPS IPsec stack detected
no known IPsec stack detected, ignoring!

**Comment by quericy** [comment]
这个是正常的，Not found是因为没有自带证书，这时脚本将调用ipsec自动生成ca证书。
如果有自己的根证书和密钥的话，放到脚本相同目录会识别并用于生成后续的其他证书。

**Comment by m13253** [comment]
> 可能你的strongswan安装有问题，而且这个脚本没有在debian下测试的

sudo apt install strongswan-pki
