### ISSUE TITLE
可以支持类似greenvpn的那种海外加速功能吗

### ISSUE THREAD

**Issue by fmyblack** [quericy/one-key-ikev2-vpn#101]
因为aws网速限制，只希望海外站点走vpn路线

**Comment by Yrr0r** [comment]
服务器是不可能的，VPN不是SS，SS使用自己的客户端，能自动给你选择网络通道，VPN没有自带的的客户端。
如果想要自动选择，只能在客户端上下功夫（客户端就无关VPN/SS了）。
一切经过服务器的请求走的都是服务器的流量，无论请求最终目的地。海外加速一般是在各种客户端上实现的，通过客户端分析请求的目的地然后将海外数据发到VPN。（类似于SS的客户端应该也有）

建议关闭这个问题，因为脚本基于Strongswan服务器，跟客户端无关。
