### ISSUE TITLE
透过ikev2 server访问本身服务的问题

### ISSUE THREAD

**Issue by xxooxxooxx** [quericy/one-key-ikev2-vpn#102]
比如，现在有样一台机器（vpn.example.com）上通过这个脚本部署了ipsec vpn server。这台机器上，还有个web server (www.example.com)。vpn.example.com，www.example.com 它们的IP地址都是指向同一个IP的，现在，如果用linux下的客户端或者Android连接到了vpn.example.com，再访问www.example.com，则无法访问，而用windows系统自带的客户端，就没有这个问题，实在不熟悉ipsec协议，有大神能解决这个问题吗?

**Comment by fdsjkl13579** [comment]
无关评论：不要把日常生产环境和VPN部署在一起

**Comment by yenwaikei** [comment]
应该是SUB域名解析的问题，因为www和VPN对于example.com来说都是一个次级域名。对于web host来说可以解析到不同的IP

**Comment by xxooxxooxx** [comment]
这个问题和内核有关，安装了最新的内核4.12.3，这个BUG自动没有了。
