### ISSUE TITLE
linode （东京新机房 kvm）vpn连接成功，但是不能上网【补充方案】

### ISSUE THREAD

**Issue by coocon** [quericy/one-key-ikev2-vpn#107]
因为自己的vps从xen 迁移到新的kvm平台，ip地址有变动，所以重新运行了一次one-key-ikev2-vpn.
发现vpn连接成功以后 不能上网。
然后根据issues中 aws的解决方法，在Linode开了一个 ticket，咨询是否是获取静态IP地址的问题。
得到答案是： 静态ip地址本身已经存在，但是仍需设置：Auto-configure Networking 为 YES。 以下是客服给的步骤，正好解决了我的问题：

if your Linode has Network Helper enabled, the configurations will automatically be set up for this IP address. To enable Network Helper:

-Log into Linode Manager
-Click on the name of the Linode
-Click on the "Shut Off" button to power the Linode down
-Click the "Edit" link to the right of the Configuration profile
-Scroll to the bottom and click the "Yes" bubble next to "Auto-configure Network"
-Click the Save button
-Power the Linode back on

**Comment by Bestoa** [comment]
检查iptables的nat表状态。
很有可能是因为原来的iptables nat表没有清空，重定向规则优先走了老IP。
`iptables -L -t nat`

**Comment by coocon** [comment]
@Bestoa 
因为一直可以连接但不能上网，所以我的  /etc/sysconfig/iptables 手动清空过。
刚才验证了一次 【Auto-configure Networking 】 设置为No， 重启linode之后发现也可以上网。
所以之前遇到的问题，应该并不是这个选项的原因， 所以 多谢Bestoa 指出。
