### ISSUE TITLE
vultr CentOS release 6.7 (Final)不能连接

### ISSUE THREAD

**Issue by jShi-git** [quericy/one-key-ikev2-vpn#11]
![1](https://cloud.githubusercontent.com/assets/3771576/13070867/a57a1bac-d4ca-11e5-810c-4e622dc26f56.png)
![2](https://cloud.githubusercontent.com/assets/3771576/13070868/a5a7e12c-d4ca-11e5-9ecf-f71a71f16180.png)
![3](https://cloud.githubusercontent.com/assets/3771576/13070926/0785ad20-d4cb-11e5-85f1-ecca09fe1713.png)
![4](https://cloud.githubusercontent.com/assets/3771576/13070985/5d747072-d4cb-11e5-9f16-c0a4efaf558c.png)

安装成功，客户端也配置好了，mac和ios都不能连接，同台服务器当前正使用pptp方式vpn不知道有没有影响

**Comment by quericy** [comment]
可能是iptables和PPTP的冲突了,建议手动配置下.
