### ISSUE TITLE
macOS下使用IKEv2和dnsmasq的问题

### ISSUE THREAD

**Issue by bindiry** [quericy/one-key-ikev2-vpn#114]
之前一直在使用此脚本在macOS上使用ikev1配置dnsmasq，效果很好，设置也很简单，只要在对应的ikev1连接设置里选择「高级」-> 「DNS Server」 -> 添加「127.0.0.1」，就可以了。

然后使用 `dig qq.com` 命令查看域名是否走了本地用dnsmasq架设的 `127.0.0.1` 的DNS服务即可。

但使用了ikev2之后，按上面所说的那样设置后，发现 `dig qq.com` 还是走的远端 `8.8.8.8` 这个DNS服务器，不能智能解析了。

请问有没有同学能够解决IKEv2和dnsmasq在macOS上配合的问题？

**Comment by luxcn** [comment]
我也是，IKEv2直接解析到8.8.8.8，导致dnsmasq本地dns解析失效。

**Comment by xlighting2017** [comment]
默认 IKEv2 所有流量都走 隧道，也就是指定的dns服务器，有2个解决方案
1. 用 apple configurator 生成IKEv2的配置文件， 其中指定 DNS相关的内容， 详见 
strongSwan Wiki
[https://wiki.strongswan.org/projects/strongswan/wiki/AppleIKEv2Profile](url)
Apple配置文件模板 - DNS Dictionary Keys
[https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206-CH1-SW27](url)

2. 将脚本中服务器下发的DNS改成 127.0.0.1,  代价是 每一个连上该服务器的客户端，都要自己开一个 dnsmasq
