### ISSUE TITLE
--enable-tools NO longer valid in strongSwan 5.3.5

### ISSUE THREAD

**Issue by terrywang** [quericy/one-key-ikev2-vpn#12]
I came across your [article](https://quericy.me/blog/512) when trying to compile the latest strongswan (5.3.5 at the moment) as the package in Ubuntu 14.04 LTS is a bit out-dated (5.1.2) and does not have the `swanctl` CLI tool introduced in 5.2.0.

Your article did help me to figure out the autoconf options to compile strongswan with needed plugins, thanks for that ;-D

Just want to point out that `--enable-tools` is no longer valid option for 5.3.5. Not exactly sure what it is but I reckon it is replaced by `--enable-swanctl` as per [Autoconf options for the most current strongSwan release](https://wiki.strongswan.org/projects/strongswan/wiki/Autoconf)

```bash
configure: WARNING: unrecognized options: --enable-tools
```

You may want to update the install script.

Anyway, I compiled 5.3.5 from source using the following autoconf configurations and it worked fine so far.

```bash

cd /path/to/strongswan-5.3.5

./configure --prefix=/usr --sysconfdir=/etc --enable-eap-identity --enable-eap-md5 \
--enable-eap-mschapv2 --enable-eap-tls --enable-eap-ttls --enable-eap-peap  \
--enable-eap-tnc --enable-eap-dynamic --enable-eap-radius --enable-xauth-eap  \
--enable-xauth-pam  --enable-dhcp  --enable-openssl  --enable-addrblock --enable-unity  \
--enable-certexpire --enable-radattr --enable-openssl --disable-gmp --enable-swanctl

make -j $(nproc)

make install
```

High recommend this article for anyone who wants to set up their own IPsec VPN using strongSwan.

[https://raymii.org/s/tutorials/IPSEC_vpn_with_CentOS_7.html](https://raymii.org/s/tutorials/IPSEC_vpn_with_CentOS_7.html)

**Comment by quericy** [comment]
Thanks a lot.
I'll update it to the dev branch.
