### ISSUE TITLE
为什么vpn连接之后能上内网，但是不能翻墙，求解！请大牛帮我看看！

### ISSUE THREAD

**Issue by cyssxt** [quericy/one-key-ikev2-vpn#133]
如题，是不是需要什么配置，我是用阿里云的美国服务器。

**Comment by Bestoa** [comment]
Please check your sysctl, enable "net.ipv4.ip_forward = 1".

**Comment by fanyer** [comment]
modify in file /etc/sysctl.conf
```
net.ipv4.ip_forward = 1
```
then, 
```
sysctl -p /etc/sysctl.conf

```
to make it take effect

**Comment by wulongji2016** [comment]
VPN 的特征明显，造就被GFW有针对的屏蔽了。

**Comment by cyssxt** [comment]
issue时间太长了 关闭

**Comment by yueguobin** [comment]
前一阵子用阿里云，ikev2的话，源目4500的数据从海外回不来，需要修改Ikev2的端口，将esp数据封装在udp中，且不能使用500/4500端口。

**Comment by yueguobin** [comment]
修改ikev2和esp的端口，不能使用500/4500的udp端口。
