### ISSUE TITLE
vpn可以正常连接，通过百度IP获取到本机也变成了VPS的美国IP，就是youtube等等需要翻墙的网页打不开

### ISSUE THREAD

**Issue by chjtwork** [quericy/one-key-ikev2-vpn#145]
vpn可以正常连接，通过百度IP获取到本机也变成了VPS的美国IP，就是youtube等等需要翻墙的网页打不开；
访问百度能成功获取到VPS的IP，说明vpn连上了也能成功转发流量，ip_forward都检查过了，不知道为什么翻墙的网站无法访问成功；并且同一台vps之前装过ss，一直用的很稳定

**Comment by yemao221** [comment]
2024年最稳定翻墙梯子VPN，翻墙2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
[![QQ20240730 - 132944](https://github.com/user-attachments/assets/d537a5f3-3ec8-4d71-b979-99a01ea8a3c9)](https://www.xxxlsop.com/#/register?code=sf9UTRC0)
