### ISSUE TITLE
WIN10连接成功但是无法上网

### ISSUE THREAD

**Issue by xuebing1995** [quericy/one-key-ikev2-vpn#166]
我大概一个月之前部署了一次，手机（iPhone IOS12）PC（Win10 64）都是可以上网的，但是就这周开始，手机连上能上网，PC连上但是不能上网了，两台笔记本都这样，都是Win10 64位的。刚才重新部署了一遍也不行。

**Comment by srx4444** [comment]
同样是这个问题……

这是VPN设置：
`PS C:\Windows\system32> Get-VpnConnection


Name                  : vv
ServerAddress         : xxx.xxx.xxx.xxx
AllUserConnection     : False
Guid                  : {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
TunnelType            : Ikev2
AuthenticationMethod  : {Eap}
EncryptionLevel       : Optional
L2tpIPsecAuth         :
UseWinlogonCredential : False
EapConfigXmlStream    : #document
ConnectionStatus      : Connected
RememberCredential    : True
SplitTunneling        : False
DnsSuffix             :
IdleDisconnectSeconds : 0`

这是IP设置：
`Windows IP 配置

   主机名  . . . . . . . . . . . . . : DESKTOP-XXXX
   主 DNS 后缀 . . . . . . . . . . . :
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   物理地址. . . . . . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 10.10.30.177(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2019年2月20日 10:58:35
   租约过期的时间  . . . . . . . . . : 2019年2月21日 10:58:35
   默认网关. . . . . . . . . . . . . : 10.10.30.1
   DHCP 服务器 . . . . . . . . . . . : 10.10.30.1
   DNS 服务器  . . . . . . . . . . . : 10.10.105.2
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

PPP 适配器 vv:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : vv
   物理地址. . . . . . . . . . . . . :
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 10.31.2.1(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.255
   默认网关. . . . . . . . . . . . . : 0.0.0.0
   DNS 服务器  . . . . . . . . . . . : 8.8.8.8
                                       8.8.4.4
   主 WINS 服务器  . . . . . . . . . : 8.8.8.8
   辅助 WINS 服务器  . . . . . . . . : 8.8.4.4
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用

以太网适配器 vEthernet (默认交换机):

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   物理地址. . . . . . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   IPv4 地址 . . . . . . . . . . . . : 172.26.133.193(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.240
   TCPIP 上的 NetBIOS  . . . . . . . : 已禁用`

**Comment by poctopus** [comment]
应该是服务器端的“net.ipv4.ip_forward=1”这个变成0了，
确认一下下面3个文件中的配置
1) /etc/sysctl.conf
2) /etc/sysctl.d/11-gce-network-security.conf
3) /etc/sysctl.d/10-ipsec.conf

**Comment by shooray** [comment]
### ‌系统服务异常‌
‌问题‌：关键网络服务未运行。
‌解决‌：
按 Win + R 输入 services.msc。
确保以下服务状态为 ‌正在运行‌：

- ‌IKE and AuthIP IPsec Keying Modules‌
- ‌Routing and Remote Access‌
- ‌**Remote Access Connection Manager‌ （这个服务）**

重启服务后重试。

### 重置网络配置‌：
以管理员身份运行：

- netsh winsock reset
- netsh int ip reset
- ipconfig /flushdns

执行完命令后，重新连接IKEv2 VPN即可上网。
