### ISSUE TITLE
腾讯云搭建无法连接。

### ISSUE THREAD

**Issue by suanve** [quericy/one-key-ikev2-vpn#168]
服务器是阿里云的，可以连接，但是没网。
开启了网络转发。
iphone
ipad
mac
连接都没问题，但是没网。

**Comment by aaab456** [comment]
亲测腾讯云搭建可以连接，有网

**Comment by DGideas** [comment]
@aaab456 阿里云腾讯云拿这个搭不会被墙吗= =，不知是否遇到过被墙的情况

**Comment by legendtang** [comment]
The same here, CN server.

**Comment by aaab456** [comment]
@DGideas 貌似还没遇到过。。这个主要是方便朋友架梯子翻回国

**Comment by DGideas** [comment]
@aaab456 哦哦，你们都是这么用的啊

**Comment by Joey-Lee** [comment]
阿里云本身shi被墙了的你搭建了服务器也没用。

**Comment by poctopus** [comment]
看看腾讯云WEB端控制台的防火墙是不是没开。
