### ISSUE TITLE
我想问一个iOS的问题

### ISSUE THREAD

**Issue by wdq123550** [quericy/one-key-ikev2-vpn#172]
我用脚本在CentOS安装好VPS客户端后，然后APP里通过证书连接，但是ios的openurl:这个方法好像打不开本地证书啊，是不是只能把证书放在服务器上，通过真正的https URL，然后用openurl:这个方法通过safari打开？
总的来说就是openurl:这个方法好像不支持本地文件路径url。。。
只能打开http/https协议的
我现在想的是把证书放本地，然后直接在APP里安装，不过好像不行啊

**Comment by mphz** [comment]
用账号密码

**Comment by quericy** [comment]
+ 可以通过邮件发送到设备上，把证书以邮件附件的形式携带；
+ 很多文件管理器都支持打开证书文件，或者分享到safari打开；
+ 苹果官方工具[iPhone configuration utility for Mac and PC](https://support.apple.com/downloads#iphone%20configuration%20utility)也可以安装证书到设备中；
