### ISSUE TITLE
建议增加 eth0 是否为公网接口的判断

### ISSUE THREAD

**Issue by StarDuster** [quericy/one-key-ikev2-vpn#18]
举个栗子，阿里云 eth0 是内网 IP，默认 eth0 的话会产生可以 VPN 连接，但是没有公网的问题。
get_my_ip 的时候判断一下 eth0 IP 是不是私有网段，或者直接加个输入网卡接口名的步骤。

**Comment by quericy** [comment]
OK,已加上选项~~
