### ISSUE TITLE
配置文件语法错误，不能启动。

### ISSUE THREAD

**Issue by brswps** [quericy/one-key-ikev2-vpn#186]
/usr/local/etc/strongswan.conf

duplicheck.enable {
                enable = no
        }

多了个enable

**Comment by quericy** [comment]
It seems to be caused by this pull request:
https://github.com/quericy/one-key-ikev2-vpn/pull/185/files#diff-90696de309779a385d825e5e93e0b1384db3e31ce184275c93fbbee9b77b2cf7R428

It has been reverted to the original version.

**Comment by brswps** [comment]
这样还是启动不了，改成这样能启动了。

 charon {
        load_modular = yes
        duplicheck {
                enable = no
        }
        compress = yes

**Comment by quericy** [comment]
Fixed. Thanks a lot.
