### ISSUE TITLE
如果採用 Letsencrypt 產生憑證之後的綁定方式

### ISSUE THREAD

**Issue by klhsu** [quericy/one-key-ikev2-vpn#195]
感謝您提供的 ikev2 server 的建置教學，現在我想透過 let's encrypt 簽發憑證，然而當憑證產生完成後，並未有 ca.cert.pem 可以使用。
否則沒有 ca.cert.pem 這個憑證檔，對於IOS 裝置就會不能被認證。
還請給我們一個指引，非常感謝。

**Comment by quericy** [comment]
The information in this article might be useful for you: https://letsencrypt.org/certificates/
