### ISSUE TITLE
choose VPS type: wrong choice!

### ISSUE THREAD

**Issue by Momosusu** [quericy/one-key-ikev2-vpn#2]
please choose the type of your VPS(Xen、KVM: 1  ,  OpenVZ: 2):
wrong choice!

Exit code: 1

---------------------------------------
 echo "please choose the type of your VPS(Xen、KVM: 1  ,  OpenVZ: 2):"
    read -p "your choice(1 or 2):" os_choice
    if [ "$os_choice" = "1" ]; then
        os="1"
		os_str="Xen、KVM"
		else
			if [ "$os_choice" = "2" ]; then
				os="2"
				os_str="OpenVZ"
				else
				echo "wrong choice!"
				exit 1
			fi
    fi

----------------------------------------------------------------------

脚本的if 和else 好像没有对齐，是这个问题么？我有点小白，或者这样同样可以键入？

**Comment by quericy** [comment]
和对齐无关...这里是用read指令读取你输入的数字来匹配选项

**Comment by Momosusu** [comment]
出现wrong choice是因为没有执行 read 指令么？

**Comment by quericy** [comment]
你选择数字了吗....

**Comment by Momosusu** [comment]
已经搞定了，开始用的 SHELL BASIC， 有些命令执行不了，换了Interactive Shell就安装成功了。我怎么才能知道strongswan是否在运行呢？用top 命令可以查看到么？

**Comment by quericy** [comment]
Ipsec status

**Comment by Momosusu** [comment]
一键安装是成功了，但是我的黑莓还是上不了，总是time out，哭死。。。。
