### ISSUE TITLE
关于 Azure VM 获取IP地址有误的问题

### ISSUE THREAD

**Issue by Renlong-Yin** [quericy/one-key-ikev2-vpn#22]
使用 Azure VM A0 主机，成安装此版本且 IOS 9 可正常连接 VPN（android_xauth_psk 形式），但故障形式为无网络访问。

`ipsec statusall` 日志如下：

```
Security Associations (1 up, 0 connecting): android_xauth_psk[4]: ESTABLISHED 10 seconds ago, 10.0.0.4[10.0.0.4]...194.129.91.141[192.168.1.107]
```

此处 `10.0.0.4` 应为 VM 的外网 ip 地址，而非为本地局域网地址，可知此处存疑。
又查 StrangSwan 监听日志为：

```
Listening IP addresses:
  10.0.0.4
  10.0.1.1
```
可知错误原因为脚本未正确获取 ip 地址。
我已作 `net.ipv4.ip_forward=1` 转发，恳请询问现在可能的解决办法。

**Comment by quericy** [comment]
Azure的网络到外网好像是有专门转发的?我不是很清楚....
脚本安装给的默认ip是通过checkip.dyndns.com获取的,如果不对的话,在安装的时候可以填写已知的公网ip.
还有网络接口也是可以手动输入的.
