### ISSUE TITLE
关于客户端连接的问题

### ISSUE THREAD

**Issue by fiht** [quericy/one-key-ikev2-vpn#26]
请问装完了怎么使用图形界面连接
客户端 ubuntu 14.04,不知道安装cert证书是什么意思..

**Comment by quericy** [comment]
就是导入CA证书
Ubuntu是可以添加可信任根证书的

**Comment by huangguan0217** [comment]
谢谢作者的projects、我就是不知道怎么把vps上的CA证书下载到本地电脑，干着急.

**Comment by quericy** [comment]
证书内容是以文本字符形式保存的,你直接cat打开文件就可以查看到里面的内容,
将内容完整的复制出来保存为相应的后缀名即可
