### ISSUE TITLE
ios 连接问题

### ISSUE THREAD

**Issue by freedomlang** [quericy/one-key-ikev2-vpn#31]
IOS 9下连接失败，查看日志发现是没有匹配到配置「`no IKE config found`」，怎么破?

安装的时候，确认服务器类型没有选错，id是默认的，c、o、cn都是默认。

**Comment by quericy** [comment]
检查一下/usr/local/etc/ipsec.conf 文件是否正常

**Comment by freedomlang** [comment]
```
conn iOS_cert
    keyexchange=ikev2
    fragmentation=yes
    left=%defaultroute
    leftauth=pubkey
    leftsubnet=0.0.0.0/0
    leftcert=server.cert.pem
    right=%any
    rightauth=pubkey
    rightauth2=xauth
    rightsourceip=10.31.2.0/24
    rightcert=client.cert.pem
    auto=add
```
本来keyexchange是ikev1的，我改了2也是不行。日志里面还是那个样子。
````
looking for an ike config for .............
resolving 'any' failed: Name or service not known
no IKE config found for.........
````

IOS上服务器和远程ID都是填VPS的ip了

**Comment by quericy** [comment]
@freedomlang iOS_cert是ikeV1的配置,ikev2用的是conn ios_ikev2 ,且手机需要导入证书
把ipsec.conf的配置信息改成 https://github.com/quericy/one-key-ikev2-vpn/blob/master/one-key-ikev2.sh#L259 
两个EOF之间的内容试试

**Comment by freedomlang** [comment]
@quericy 忘了说，证书是已经导入到手机了「也就是描述文件」，ipsec.conf的配置信息改成你所说的也还是一样连不上>_<

PS：改完ipsec.conf后，我是reload过的！

**Comment by quericy** [comment]
这种情况确实比较奇怪,建议make uninstall卸载了,清除相关文件,再重新下载最新版本编译安装试试

**Comment by quericy** [comment]
脚本已更新，iOS9/10测试通过，有兴趣的话可以试试

**Comment by tisfeng** [comment]
请问一下，远程ID是什么，没看到文档说明啊
