### ISSUE TITLE
ikev2 && oneinstack 存在冲突

### ISSUE THREAD

**Issue by codesboy** [quericy/one-key-ikev2-vpn#33]
我发现ikev2和oneinstack lamp环境(https://oneinstack.com/install).存在冲突，如果我先安装lamp,再一键安装IPSEC/IKEV2 VPN服务器，那么VPN服务器就死活安装不成功，如果我先安装VPN再安装oneinstack ，那么lamp环境就会出现问题。
我的是Centos 6 x86 minimal

**Comment by quericy** [comment]
和其他一键脚本的共存暂不在兼容性考虑范围之内
建议手动安装和修改iptables
