### ISSUE TITLE
我用的是Azure，类型为Hyperv

### ISSUE THREAD

**Issue by wydwww** [quericy/one-key-ikev2-vpn#35]
请问这个应该怎么办？

**Comment by quericy** [comment]
没有用过HyperV的Server,所以脚本并没有考虑除了OpenVZ和Xen,KVM以外的vps.
当然这两种类型在脚本处理上的区别主要是编译参数和生成iptables选择的网卡地址
不过你可以尝试类型选择Xen、KVM看看
