### ISSUE TITLE
Linode Ubuntu16.04，安装好之后，依然是8分钟掉线。

### ISSUE THREAD

**Issue by yanlongchn** [quericy/one-key-ikev2-vpn#38]
反馈：
8分钟依然掉线
大神解决一下吧，谢谢你了。

**Comment by quericy** [comment]
这里并没有重现此问题. 
而且更改了dh14 加密以后,iOS9也不应该再8分钟断线了
麻烦提供一下客户端系统和版本,以及断线时间点前后的日志信息

**Comment by wuxinli1025** [comment]
Mac OS X 10.11.6
Linux strongSwan U5.3.5/K2.6.32-042stab116.1
链接ikev2后分配到ios_ikev2
505秒后短线
服务器端无日志产生
之后服务器端发送DPD， 然后检测不到活跃链接
最后: 11[CFG] lease 10.31.2.1 by '*****************' went offline
ios_ikev2 段配置如下
conn ios_ikev2
    keyexchange=ikev2
    ike=aes256-sha256-modp2048,3des-sha1-modp2048,aes256-sha1-modp2048!
    esp=aes256-sha256,3des-sha1,aes256-sha1!
    rekey=no
    left=%defaultroute
    leftid=**domain.com**
    leftsendcert=always
    leftsubnet=0.0.0.0/0
    leftcert=fullchain.pem
    right=%any
    rightauth=eap-mschapv2
    rightsourceip=10.31.2.0/24
    rightsendcert=never
    eap_identity=%any
    dpdaction=clear
    fragmentation=yes
    auto=add

**Comment by quericy** [comment]
Strongswan已经更新到5.5.1,按官方的说法应该解决了这个问题
