### ISSUE TITLE
Script Doesn't Start After Server Restart

### ISSUE THREAD

**Issue by XPOTiFY** [quericy/one-key-ikev2-vpn#40]
Hey man, 

Thanks a lot for this awesome script, however I have some problem regarding the script startup.
After I restart the server, the VPN server does not respond anymore.
I have tried
`ipsec restart`
and
`/usr/local/sbin/ipsec restart`
still no go :(
Here is the windows 10 error:
The network connection between your computer and the VPN server could not be established because the remote server is not responding [...].
Server -> Ubuntu 16.04 OpenVZ X64

**Comment by quericy** [comment]
@XPOTiFY You might need to check your server iptables rules setting.
