### ISSUE TITLE
你好，请问用购买的通配符证书该如何配置呢？

### ISSUE THREAD

**Issue by jg168** [quericy/one-key-ikev2-vpn#41]
你好，购买了通配符证书，该怎么用呢？

**Comment by quericy** [comment]
证书应该要有颁发策略才能使用.
普通的泛域名证书只是用于证明身份的应该不行

**Comment by jg168** [comment]
颁发策略指的是什么呢？没见过这样的证书呢

**Comment by jg168** [comment]
我尝试过在windows2008上用泛域名证书配置，配置成功

**Comment by quericy** [comment]
@jg168  看下脚本以下几行：
[https://github.com/quericy/one-key-ikev2-vpn/blob/master/one-key-ikev2.sh#L249-L253](https://github.com/quericy/one-key-ikev2-vpn/blob/master/one-key-ikev2.sh#L249-L253)

将你的证书按以下规则命名并替换到脚本那几行的目录下：
ca.cert.pem 证书办法机构的CA，比如Let's Encrypt的CA证书
server.cert.pem 签发的域名证书
server.pem 签发域名证书时用的私钥
client.cert.pem 签发的域名证书
client.pem 签发域名证书时用的私钥

然后重启ipsec服务
