### ISSUE TITLE
找到个bug，给你说下

### ISSUE THREAD

**Issue by hoore** [quericy/one-key-ikev2-vpn#43]
centos 下，首次安装不重启服务器，工作正常。重启后无法翻墙。目测是路由表加的顺序问题，手动调整/etc/sysconfig/iptables，再重启，一切OK，代码这块你改下。另外交个朋友。加我好友，谢谢啦。

**Comment by hoore** [comment]
另外阿里云centos32 路由默认重启不开启，最好补一句 chkconfig iptables on

**Comment by quericy** [comment]
嗯,脚本是没有考虑iptables本身不工作的情况的
