### ISSUE TITLE
/root/my_key/ca.cert.pem zero disk

### ISSUE THREAD

**Issue by Julyyq** [quericy/one-key-ikev2-vpn#44]
提示这个证书大小为0诶

**Comment by quericy** [comment]
可能是ipsec pki指令中的某一步没有执行成功,或者也可能是strongswan安装有问题

可以试着手动执行脚本里的ipsec pki 命令生成证书,然后看看错误信息.

**Comment by Julyyq** [comment]
@quericy 运行`bash one-key-ikev2.sh`之前，没有安装strongswan, 安装后在运行shell就OK了。非常感谢。
