### ISSUE TITLE
macos sierra让ikev2无法工作了

### ISSUE THREAD

**Issue by asmc** [quericy/one-key-ikev2-vpn#45]
苹果为了安全，不仅吧pptp拿掉了，而且那个eap-mschapv2也应该去掉了，，
目前vpn瘫痪中，，正在研究如何弄，大表哥看看咋解决呢

**Comment by marks-yag** [comment]
绝望中，再不行就得考虑openproxy了，我手欠点啥升级啊  :(

**Comment by marks-yag** [comment]
我是说openvpn，唉

**Comment by asmc** [comment]
哈，解决了，忘记说了，升级ca证书失效，你重新让他始终信任就可以了：）折腾了好久才发现的这里的问题，我也是醉了

**Comment by marks-yag** [comment]
为啥我的不行啊：（，现在已经l2tp，暂时先这么着吧，问候一遍方校长再。

**Comment by quericy** [comment]
脚本已更新，可以试试使用SSL证书，就不需要像自签名证书那样添加信任了。
