### ISSUE TITLE
use real ssl for ikev2

### ISSUE THREAD

**Issue by mohamad77** [quericy/one-key-ikev2-vpn#47]
Hello
i got a ssl from comodo
(ssl files are ca_bundle.crt , certificate.crt , private.key )
how can i set them for strongswan ikev2?
thanks

**Comment by quericy** [comment]
@mohamad77 Hello
you just need to replace these .pem file in [https://github.com/quericy/one-key-ikev2-vpn/blob/master/one-key-ikev2.sh#L249-L253](https://github.com/quericy/one-key-ikev2-vpn/blob/master/one-key-ikev2.sh#L249-L253) : 

ca.cert.pem : The CA root cert(ca_bundle.crt)
server.cert.pem : Your server cert(certificate.crt)
server.pem : Your server private key of the cert(private.key)
client.cert.pem : Your server cert(certificate.crt)
client.pem : Your server private key of the cert(private.key)

And then, restart your ipsec service.
