### ISSUE TITLE
请问安卓用strongswan vpn client连接ikev2如何配置？

### ISSUE THREAD

**Issue by jg168** [quericy/one-key-ikev2-vpn#48]
请问安卓用strongswan vpn client连接ikev2  ipsec.conf里面该如何配置呢？

**Comment by quericy** [comment]
我没有安卓设备，安卓原生的配置仅支持IkeV1。

使用strongswan vpn client连接的话，在模拟器上试验了下是可以正常使用的，除了安卓4.4有bug
真实机器我就不知道了

先下载[strongSwan VPN Client](https://apkpure.com/search?q=strongswan)安装并运行

如果使用自签名证书需要先导入ca.cert.pem，使用SSL证书则无需导入

然后输入服务器地址，EAP的用户名和密码即可
