### ISSUE TITLE
no netkey IPsec stack detected when run ipsec

### ISSUE THREAD

**Issue by chaov** [quericy/one-key-ikev2-vpn#56]
Hi,
Did you encounter that issue, missing ipsec stack, so ipsec can't run.
My OS is Ubuntu 14.04 x86_64.
[root@www:/home/vpn/strongswan# ipsec status                
Security Associations (0 up, 0 connecting):
  none
root@www:/home/vpn/strongswan# ipsec restart
Stopping strongSwan IPsec...
Starting strongSwan 5.5.1 IPsec [starter]...
no netkey IPsec stack detected
no KLIPS IPsec stack detected
no known IPsec stack detected, ignoring!
root@www:/home/vpn/strongswan# 
root@www:/home/vpn/strongswan# 
root@www:/home/vpn/strongswan# uname -a
Linux www 2.6.32-042stab108.5 #1 SMP Wed Jun 17 20:20:17 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks,
Chao

**Comment by quericy** [comment]
I think you could ignore these warning.It doesn't affect the IPsec connection.

**Comment by towry** [comment]
It affect.

**Comment by kielsoft** [comment]
Please any solution to this... its also affecting me connection too

**Comment by chinazj** [comment]
the same with me .how do it?
