### ISSUE TITLE
安装完成后，mac不能连接

### ISSUE THREAD

**Issue by cleexiang** [quericy/one-key-ikev2-vpn#58]
已经安装完成，并把ca.cert.pem下载到本地，尝试用证书鉴定设置，发现列表里面没有显示该证书，keychain里面也是显示该证书不被信任，又尝试用用户名和密码登录，也连接不上，请问怎么解决呢？

**Comment by free007** [comment]
@cleexiang 我跟你一样的问题

**Comment by cleexiang** [comment]
@free007 你解决了吗

**Comment by JiaHaoGong** [comment]
这个就是证书信任的问题,如图所示将对应的证书设置为始终信任,就可以成功了.
![solveissuse](https://cloud.githubusercontent.com/assets/14161999/20522691/9c196c58-b0ec-11e6-8418-dd1e55a8ff65.png)

**Comment by quericy** [comment]
@cleexiang @free007 自签名证书在客户端导入时,要设置在信任的存储区,无论是Windows还是Mac都是如此.或者使用信任的机构颁发的SSL证书就无需在客户端导入证书.

@JiaHaoGong 感谢提供Mac添加信任证书的截图.

**Comment by njdragonfly** [comment]
Mac电脑下已经选择了信任，还是不能导入正式是啥问题？

**Comment by wanghe826** [comment]
您好，关于机构颁发的SSL我有个问题一直搞不明白。就是“或者使用信任的机构颁发的SSL证书就无需在客户端导入证书”，这里的无需在客户端倒入证书是什么意思啊？ 是不是客户端只需要设置账号和密码了？但是我一直连不上啊，查看服务器日志显示“no matching peer config found”
