### ISSUE TITLE
安装完成后连不上

### ISSUE THREAD

**Issue by chunhui2001** [quericy/one-key-ikev2-vpn#61]
我按照你的安装步骤一步一步安装成功了，但是当我尝试在 ios 手机上用 ikev2 连接的时候总也连不上! 不知道是怎么回事! 也不知道怎么调试! 

每次连接的时候我想通过 tail -f /var/log/syslog 或 tail -f /var/log/auth.log 看不到任何连接信息!

ipsec 也启动了:
**_sudo ipsec status
Security Associations (0 up, 0 connecting):
  none_**

**Comment by quericy** [comment]
如果没有连接信息的话,应该问题出现在iptables上,检查一下入站规则吧
不过也有可能是客户端所出的网络问题
