### ISSUE TITLE
tar bug

### ISSUE THREAD

**Issue by hqlulu** [quericy/one-key-ikev2-vpn#64]
小意外，如果目录有 strongswan-5.3.3
那脚本就有错误了，无法进行，既然下载指定了 5.5.1，tar命令也指定好了

**Comment by quericy** [comment]
感谢反馈!
不过话说什么情况下才会原目录下还有其他版本的strongswan.....

**Comment by hqlulu** [comment]
我之前有下载旧版本安装，没成功，后来用你的一键安装
发现执行到这里就出错了，看脚本才知道是写法有问题
我删除掉旧文件，就正常了

**Comment by quericy** [comment]
原来如此~~
这个写法是有问题,上次修改压缩文件命名的时候只改了前半部分
脚本已经更新
