### ISSUE TITLE
Mac OSX 10.11.6 无法连接

### ISSUE THREAD

**Issue by lili520** [quericy/one-key-ikev2-vpn#65]
安装完成之后iPhone和iPad是可以正常连接和上网的，Mac却不能连接成功，Mac上面证书已安装并且也设置了始终信任。 服务器为linode上面的CentOS 7。

请大神看下能有解决方法没，下面是部分Log，IP 110.110.110.110为本机IP，IP 120.120.120.120为VPN服务器IP

Nov 27 12:43:59 localhost charon: 09[NET] received packet: from 110.110.110.110[500] to 120.120.120.120[500] (604 bytes)

Nov 27 12:43:59 localhost charon: 09[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(REDIR_SUP) N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]

Nov 27 12:43:59 localhost charon: 09[IKE] 110.110.110.110 is initiating an IKE_SA

Nov 27 12:43:59 localhost charon: 09[IKE] remote host is behind NAT

Nov 27 12:43:59 localhost charon: 09[IKE] sending cert request for "C=com, O=myvpn, CN=VPN CA"

Nov 27 12:43:59 localhost charon: 09[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(MULT_AUTH) ]

Nov 27 12:43:59 localhost charon: 09[NET] sending packet: from 120.120.120.120[500] to 110.110.110.110[500] (473 bytes)

Nov 27 12:44:29 localhost charon: 16[JOB] deleting half open IKE_SA after timeout

**Comment by quericy** [comment]
发送回包没有响应,你的Mac和其他可以连接的设备是处于相同的网络环境吗?

**Comment by lili520** [comment]
@quericy 是的，都处于同一个网络下面。

**Comment by lili520** [comment]
重启了路由器，重启了电脑，然后就神奇的连上了。。。速度还可以的，最高3M平均1.5M，看视频很流畅。
