### ISSUE TITLE
charon.compress 选项在文档中并没有搜到

### ISSUE THREAD

**Issue by fanchangyong** [quericy/one-key-ikev2-vpn#67]
你好，在 `strongswan.conf` 这个文件中，我看到你添加了一个选项是: `compress = yes`，但我从文档中并没有搜索到有 `charon.compress` 这个配置选项。请问这个选项是被废弃了，还是怎么回事？
谢谢！

**Comment by quericy** [comment]
应该还没有废弃
https://wiki.strongswan.org/projects/strongswan/wiki/ConnSection
