### ISSUE TITLE
安装完成后，连接不上

### ISSUE THREAD

**Issue by LeoXu92** [quericy/one-key-ikev2-vpn#68]
按照步骤完成后，MAC连不上VPN，已经安装了证书，并设置为了信任。我应该如何开始查找问题。

**Comment by LeoXu92** [comment]
centos7.0 安装后连接不上，centos6.5没有问题。

**Comment by quericy** [comment]
CentOS7如果使用FIREWALLD 可能是存在兼容问题.脚本仅针对iptables生成的.

**Comment by quericy** [comment]
见 #70

**Comment by LeoXu92** [comment]
好的。谢谢。
