### ISSUE TITLE
iptables 路由转发部分的兼容性问题

### ISSUE THREAD

**Issue by wuxianlijiang** [quericy/one-key-ikev2-vpn#69]
我是固定ip（腾讯云），选择1安装后，vpn连接正常，不能上外网。经查，是本段脚本中的区别判断问题：

`        #iptables -A FORWARD -j REJECT
        if [ "$use_SNAT_str" = "1" ]; then
            iptables -t nat -A POSTROUTING -s 10.31.0.0/24 -o $interface -j SNAT --to-source $static_ip
            iptables -t nat -A POSTROUTING -s 10.31.1.0/24 -o $interface -j SNAT --to-source $static_ip
            iptables -t nat -A POSTROUTING -s 10.31.2.0/24 -o $interface -j SNAT --to-source $static_ip
        else
            iptables -t nat -A POSTROUTING -s 10.31.0.0/24 -o $interface -j MASQUERADE
            iptables -t nat -A POSTROUTING -s 10.31.1.0/24 -o $interface -j MASQUERADE
            iptables -t nat -A POSTROUTING -s 10.31.2.0/24 -o $interface -j MASQUERADE
        fi`

因为：把iptables配置文件中由脚本生成的三行配置注释后，添加第四行后正常，如：
`:OUTPUT ACCEPT [0:0]
#-A POSTROUTING -s 10.31.0.0/24 -o eth0 -j SNAT --to-source 123.207.236.57
#-A POSTROUTING -s 10.31.1.0/24 -o eth0 -j SNAT --to-source 123.207.236.57
#-A POSTROUTING -s 10.31.2.0/24 -o eth0 -j SNAT --to-source 123.207.236.57
**-A POSTROUTING -s 10.31.2.0/24 -o eth0 -j MASQUERADE**`

**Comment by wuxianlijiang** [comment]
因此，仅判断   eth名称， 直接以  -A POSTROUTING -s 10.31.2.0/24 -o eth0 -j MASQUERADE  转发即可。

**Comment by quericy** [comment]
这个是你安装的时候选了SNAT,但是没有修改ip选项
如果你不选择使用SNAT,生成的就是MASQUERADE 的规则;
使用SNAT仅为了提升iptables的处理效率,前提是要清楚转发的地址,并不绝对是固定ip,如果机房有再做转发或者弹性ip的策略,安装的时候就要对应调整的.
