### ISSUE TITLE
不兼容CENTOS 7 FIREWALLD

### ISSUE THREAD

**Issue by laygle** [quericy/one-key-ikev2-vpn#70]
看了下脚本，只有IPTABLES的规则

**Comment by quericy** [comment]
是的,我并不熟悉firewalld,也没有使用CentOS7,目前脚本仅支持用iptables.
 如果你有比较好的firewalld的修改方案也欢迎交流分享.

**Comment by zhjch05** [comment]
```
firewall-cmd --permanent --add-service="ipsec"
firewall-cmd --permanent --add-port=4500/udp
firewall-cmd --permanent --add-masquerade
firewall-cmd --reload
```
用firewalld打开对应的规则、端口即可
参考我的配置和Vultr官方指南
https://www.vultr.com/docs/using-strongswan-for-ipsec-vpn-on-centos-7
https://www.jczhang.com/2017/01/05/77en/

**Comment by quericy** [comment]
@zhjch05 感谢提供方案，脚本已添加firewall的规则 #81
