### ISSUE TITLE
[Debian]Reboot the system, the sysctl option(net.ipv4.ip_forward=1) is missing.

### ISSUE THREAD

**Issue by Bestoa** [quericy/one-key-ikev2-vpn#71]
If the user doesn't modify the default value of "/etc/sysctl.conf" in Debian and reboots his VPS, he could just connect to the VPN but can't surf the Internet.

**Comment by quericy** [comment]
Thanks for your suggestion. I think it might be a better way to create a new config file in /etc/sysctl.d/10-*.conf

**Comment by quericy** [comment]
Fixed in #81 .
