### ISSUE TITLE
Mac OSX 下连接失败的原因？

### ISSUE THREAD

**Issue by nxtreaming** [quericy/one-key-ikev2-vpn#74]
使用SSL 证书方式。在windows可以正常登录使用，在Mac下不能登录使用。

请问最有可能是什么原因导致？

我的SSL证书签名是  xxxxx.com 域名方式。

谢谢！

**Comment by nxtreaming** [comment]
I found the reason.

It is the bug of Mac OS X ( OS X 10.11 EI Capitan ), 10.11 does not support IKE V2 even if it shows the IKE V2 option in VPN configuration.

It is fine after I upgrade to macSierra (10.12)

**Comment by Bestoa** [comment]
今天发现了一个可以workaround的办法。
SSL证书签的是xxxx.com，然后绑定xxxx.com/yyy.xxxx.com都是到VPN服务器。建立VPN的时候，用xxxx.com和证书。MacOS 10.11的客户端上，域名填yyy.xxxx.com, RemoteID还是xxxx.com,可以正常使用
