### ISSUE TITLE
一些不必要的端口和网段是否可以去掉

### ISSUE THREAD

**Issue by sjtuross** [quericy/one-key-ikev2-vpn#75]
对于IKEv2的VPN来说，只要允许UDP 500和UDP 4500端口就可以了，下面的代码是否可以去除呢？
```
iptables -A INPUT -i $interface -p tcp --dport 500 -j ACCEPT
iptables -A INPUT -i $interface -p udp --dport 1701 -j ACCEPT
iptables -A INPUT -i $interface -p tcp --dport 1723 -j ACCEPT
```
另外10.31.0.0/24和10.31.1.0/24这两个网段并没有用到，是否也可以把相关的iptables语句去除呢？

非常感谢你的脚本，只是希望它更完美！

**Comment by itiger88** [comment]
你自己可以去掉就行，作者之前可能有pptp、l2tp放在同一台vps中，所以保留了这2个协议需要的端口

**Comment by quericy** [comment]
是的,可以自行剔除.
脚本改动过很多次,一些端口没有删也是考虑有些人同时安装了多个类型的服务

**Comment by Liashui** [comment]
@sjtuross  为什么ikev2不需要允许tcp通过，知识udp呢？
