### ISSUE TITLE
ifconfig: command not found

### ISSUE THREAD

**Issue by alipora** [quericy/one-key-ikev2-vpn#76]
Hello
" if " Should be replaced by " ip "
one-key-ikev2.sh: line 447: ifconfig: command not found
one-key-ikev2.sh: line 461: ifconfig: command not found
OS : CENTOS 7

**Comment by Bestoa** [comment]
Suggest to use "ip" instead of "ifconfig".

**Comment by quericy** [comment]
已修复 #81
