### ISSUE TITLE
Ubuntu 16.10 下可认证通过，但是无法上网

### ISSUE THREAD

**Issue by CodeRhm** [quericy/one-key-ikev2-vpn#77]
服务端：vultr 主机 ubuntu 16.10
客户端：Android 6.0.1（Xauth），Windows 10（IKEv2）
都不行，都是能连上vpn，但是无法访问网络。
但部署的SS可以正常使用，并不清楚16.10使用的是什么防火墙，感觉应该未启用iptables。

**Comment by richars** [comment]
可连接但是无法访问网络：

检查iptables是否正常启用,检查iptables规则是否与其他地方冲突,或根据服务器防火墙的实际情况手动修改配置。
检查sysctl是否开启ip_forward:
打开sysctl文件:vim /etc/sysctl.conf
修改net.ipv4.ip_forward=1后保存并关闭文件
使用以下指令刷新sysctl：sysctl -p
如执行后正常回显则表示生效。如显示错误信息，请重新打开/etc/syctl并根据错误信息对应部分用#号注释，保存后再刷新sysctl直至不会报错为止。

**Comment by richars** [comment]
我碰到过同样的问题，这样就OK了。

**Comment by WinAu** [comment]
的确跟系统有关……我用的是16.04也是不行，只能连接不能上网，--nofork输出的只有连接上的时候，过一分钟就自动断开了，换成了14.04同样的步骤再配置以便就可以上了

**Comment by ren2881971** [comment]
@CodeRhm 我的也是 ubuntu 16  ios 使用ipsec 可以连接vpn 但是ikev2 就不行。
我也怀疑是 ubuntu 的 iptables 没有启动。

**Comment by Bestoa** [comment]
@ren2881971 根据个人测试经验ikev2的穿透力似乎不如ipsec。同样网络环境下，多次ikev2无法穿透，ipsec正常。建议换个网络环境测试。

**Comment by ren2881971** [comment]
@Bestoa 那不应该啊 ios的IPSec 不是指的是ikev1么？  而ikev2是指更新的版本 version2.0。难道我学的知识不对，，，

**Comment by Bestoa** [comment]
你理解的没错。
