### ISSUE TITLE
如何只能使用用户名和密码登录?

### ISSUE THREAD

**Issue by alex1528** [quericy/one-key-ikev2-vpn#79]
如题. ios_ikev2客户端

**Comment by quericy** [comment]
配置/usr/local/etc/ipsec.secrets的 EAP 部分的用户名和密码，申请使用SSL证书便不需要安装证书部分了

**Comment by alex1528** [comment]
不是这个意思,是客户端如果选择用了证书(let's encrypt的证书)方式登录, 就不用用户名和密码了, 这样的话, 如果vpn对外, 是不是任何人就可以登录私有vpn了?

**Comment by quericy** [comment]
@alex1528 使用SSL证书仍然需要用户名密码的,只是免去客户端添加对自签名证书信任的繁琐步骤,仍然需要EAP或PSK方式验证授权. 
参见 [客户端配置说明](https://github.com/quericy/one-key-ikev2-vpn#客户端配置说明) 一节
