### ISSUE TITLE
安装完成后，证书文件ca.cert.pem是0字节

### ISSUE THREAD

**Issue by thetcc** [quericy/one-key-ikev2-vpn#80]
安装完成后，/root/my_key 下的所有文件都是0字节。
-rw-r--r--. 1 root root 0 1月  24 16:30 ca.cert.pem
-rw-r--r--. 1 root root 0 1月  24 16:30 ca.pem
-rw-r--r--. 1 root root 0 1月  24 16:30 client.cert.p12
-rw-r--r--. 1 root root 0 1月  24 16:30 client.cert.pem
-rw-r--r--. 1 root root 0 1月  24 16:30 client.pem
-rw-r--r--. 1 root root 0 1月  24 16:30 server.cert.pem
-rw-r--r--. 1 root root 0 1月  24 16:30 server.pem
这个就肯定无法在客户端进行导入了。请问怎么解决？

系统CentOS release 6.4 (Final)，物理机，非虚拟机。
你的一键安装脚本里选择XEN方式，其他基本都是一路回车。

**Comment by quericy** [comment]
重装一下Strongswan,然后手动安装证书或者重新执行脚本

**Comment by xuzixx** [comment]
我遇到了一样的情况，我的问题是系统自带一个ipsec 版本特别低，导致生成证书命令失败。
