### ISSUE TITLE
[求助] ubuntu 作为客户端可以连接，可以得到IP，不能通过VPN上网。

### ISSUE THREAD

**Issue by safeie** [quericy/one-key-ikev2-vpn#85]
首先服务端，win10, iphone, mac都测试过上网没问题。

还有ubuntu linux作为 客户端，一直没搞定，跪求帮忙。

client ipsec.conf

```
conn toserver
    keyexchange=ikev2
    ike=aes256-sha256-modp2048,3des-sha1-modp2048,aes256-sha1-modp2048!
    esp=aes256-sha256,3des-sha1,aes256-sha1!
    rekey=no
    left=%any
    leftsourceip=0.0.0.0
    leftsubnet=0.0.0.0/0
    leftfirewall=yes
    leftsendcert=never
    leftauth=eap-mschapv2
    right=47.90.120.12
    rightid=47.90.120.12
    rightsubnet=0.0.0.0/0
    rightsendcert=always
    eap_identity=dev
    dpdaction=clear
    fragmentation=yes
    auto=start
```

client ipsec.secret

```
dev 47.90.120.12 : EAP "helloword"
```

另外，导入了 server的ca.cert.pem 到 /usr/local/etc/ipsec.d/cacerts 目录中

重新启动 ipsec start 可以连接成功，得到IP地址： 10.31.2.1

server端查看 status 可以看到：

```
~# ipsec status  
Security Associations (2 up, 0 connecting):
   ios_ikev2[34]: ESTABLISHED 9 seconds ago, 172.31.98.180[47.90.120.12]...120.77.171.23[172.18.110.74]
   ios_ikev2{38}:  INSTALLED, TUNNEL, reqid 21, ESP in UDP SPIs: c7aa494b_i c861b147_o
   ios_ikev2{38}:   0.0.0.0/0 === 10.31.2.1/32
```

但是 ubuntu client没有路由，我设置默认路由为 10.31.2.1 也不起作用，无法通过VPN上网。

求助。。。

**Comment by safeie** [comment]
已解决了，VPN的配置没有问题，原因是VPN的IP段和ALIYUN的私有IP冲突，ALIYUN太狠了，10.0.0.0/8，10段的不要玩了。

**Comment by LuCnNew** [comment]
您好，请问ubuntu怎么运行客户端？

**Comment by hunhun010164** [comment]
您好,
我现在正在用openwrt+strongswan做IKEv2/IPSec客户端配置,发现故障现象和你的一模一样,但是我的:
服务器1是一台VPS,没有LAN IP,也不存在10网段的问题
服务器2是烽火HG320刷openwrt+strongswan搭建的,WAN是192.168.0网段,LAN是192.168.218网段,通过端口转发UDP500和4500,不存在10网段
服务器3是newifi d2刷openwrt+strongswan搭建的,是主路由,WAN静态IP:10.254.9.11,问运营商要了公网IP,估计是DMZ到10.254.9.11上去的.也算是没有10网段的问题吧.
三个服务器用windows,苹果,手机客户端都验证过没问题.

但是我这台openwrt+strongswan做VPN客户端的路由器,连上服务器后,路由表上既没有添加网关,也无法通过VPN上网,看了您的解决方案但又觉得我的服务器都没有10网段的问题,所以很迷茫,麻烦能否指点一下.谢谢

另外,我有个疑问,您这里,既然windows,手机客户端在VPN服务器有10网段的情况下都能上网,为啥Linux客户端就会受到影响呢?谢谢

**Comment by hunhun010164** [comment]
另外,这个路由器经常无故重启,好烂,联想就是垃圾
