### ISSUE TITLE
ike无法找到有效的计算机证书

### ISSUE THREAD

**Issue by xiedeacc** [quericy/one-key-ikev2-vpn#86]
amazon ec2 ubuntu 16.04 使用一键搭建脚本，安装过程没有出问题，选的是xen，自己生成证书，也导入根证书成功了，但是win10选择IKEV2方式连接vpn时，提示ike找不到合适的证书，无法连接VPN。请问是证书没有导入成功还是什么问题

**Comment by quericy** [comment]
证书导入问题，排查以下两点：
+ 证书导入时选`计算机账户`
+ 导入区域为`受信任的根证书颁发机构`
+ 连接属性的身份验证选`EAP-MSCHAP v2`

**Comment by xiedeacc** [comment]
非常感谢 证书的问题是因为没放在电脑根证书

Get Outlook for iOS




On Thu, Mar 23, 2017 at 4:14 PM +0800, "quericy" <notifications@github.com> wrote:












证书导入问题，排查以下两点：

证书导入时选计算机账户
导入区域为受信任的根证书颁发机构
连接属性的身份验证选EAP-MSCHAP v2
