### ISSUE TITLE
Wi-Fi能连上不能上网，4G则可以

### ISSUE THREAD

**Issue by vinqon** [quericy/one-key-ikev2-vpn#88]
iptables和sysctl都确定设置正确，前几个月Wi-Fi和4G一直都能上的，最近Wi-Fi能连上但不能连外网
我的VPN部署了在几个VPS上，包括阿里云，搬瓦工，vultr和星光互联，它们都出现了这个情况
已经尝试更换Wi-Fi的路由器，并且检查了没有阻止VPN连接，但问题依然存在
Wi-Fi使用的是深圳电信，4G是深圳联通，会跟运营商有关吗？

**Comment by Liashui** [comment]
@vinqon  你是centos还是ubuntu？

**Comment by vinqon** [comment]
Centos @Liashui

**Comment by Liashui** [comment]
我想请教你一个问题，但是对你这个问题没有帮助，我现在没有vps，直接虚拟机上面测试的，安装不成功，你是用了这个脚本安装配置的嘛？

**Comment by quericy** [comment]
不同网络环境下使用的是什么设备？
