### ISSUE TITLE
脚本运行完成，ipsec启动不成功

### ISSUE THREAD

**Issue by Liashui** [quericy/one-key-ikev2-vpn#89]
你在centos7运行有没有问题吗？脚本执行过程中可疑的地方贴出来 （我现在没有vps，我自己安装vmware funsion测试的，我的os类型选择了1，因为我没有查询到vmware funsion采用了什么虚拟技术）
1
warning: remember to run 'libtool --finish /usr/lib/ipsec/plugins'
2
/usr/local/sbin/ipsec:行184: /usr/sbin/ipsec: 没有那个文件或目录
/usr/local/sbin/ipsec:行187: /usr/sbin/ipsec: 没有那个文件或目录
3
/usr/local/sbin/ipsec:行219: /usr/libexec/ipsec/starter: 没有那个文件或目录

下面是提示成功的消息
#############################################################

[Install Complete]
Version:1.2.0
There is the default login info of your IPSec/IkeV2 VPN Service
UserName: myUserName
PassWord: myUserPass
PSK: myPSKkey
you should change default username and password in /usr/local/etc/ipsec.secrets
you cert: /root/my_key/ca.cert.pem
you must copy the cert to the client and install it.

#############################################################

**Comment by Liashui** [comment]
我最后没有用脚本，一步一步来成功了  按照http://bbs.pceva.com.cn/thread-130112-1-1.html

提示信息
[root@localhost strongswan]# service strongswan status
● strongswan.service - strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf
   Loaded: loaded (/usr/lib/systemd/system/strongswan.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2017-03-15 03:42:32 EDT; 12min ago
  Process: 81550 ExecStart=/usr/sbin/ipsec start --nofork (code=exited, status=0/SUCCESS)
 Main PID: 81550 (code=exited, status=0/SUCCESS)

Mar 15 03:42:32 localhost.localdomain systemd[1]: Started strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf.
Mar 15 03:42:32 localhost.localdomain systemd[1]: Starting strongSwan IPsec IKEv1/IKEv2 daemon using ipsec.conf...
Mar 15 03:42:32 localhost.localdomain ipsec_starter[81550]: Starting strongSwan 5.5.1 IPsec [starter]...
Mar 15 03:42:32 localhost.localdomain ipsec[81550]: Starting strongSwan 5.5.1 IPsec [starter]...
Mar 15 03:42:32 localhost.localdomain ipsec[81550]: charon is already running (/var/run/charon.pid exists) -- skipping daemon start
Mar 15 03:42:32 localhost.localdomain ipsec_starter[81550]: charon is already running (/var/run/charon.pid exists) -- skipping daemon start
Mar 15 03:42:32 localhost.localdomain ipsec[81550]: starter is already running (/var/run/starter.charon.pid exists) -- no fork done

但是我在ios，mac上面测试连接不上，有没有遇到类似情况的？

**Comment by Liashui** [comment]
虚拟机网卡信息
ip a

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:9f:13:29 brd ff:ff:ff:ff:ff:ff
    inet 192.168.176.128/24 brd 192.168.176.255 scope global dynamic ens33
       valid_lft 1750sec preferred_lft 1750sec
    inet6 fe80::4def:dc53:7bc7:3649/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by vinqon** [comment]
建议你找个vps跑吧，我看你的网卡名称有点问题，没见过ens33这样的。
脚本好像写死了eth0或者venet0的，你或者自己改一下试试。

**Comment by vinqon** [comment]
不用自己改，看到下面这个提示写ens33看看。
Network card interface(default_value:eth0)

**Comment by Liashui** [comment]
@vinqon   centos7虚拟机下面 网卡就是ens33的，我正打算买vps，可是还没有visa，正在申请招商的visa，网卡名称可以配置的，安装脚本过程中会提示的，你是centos6还是centos7？

**Comment by vinqon** [comment]
centos6 64x

**Comment by Liashui** [comment]
@vinqon   谢谢，我这vps没来之前，我在debian8上面测试下吧

**Comment by Liashui** [comment]
@vinqon 

debian8下面测试成功，ikev1/ikev2都能连接上,开启vpn之后，速度感觉慢好多，你那边速度怎么样呢？

**Comment by quericy** [comment]
Install Complete 仅表示脚本运行完毕，中间过程是否有问题还需要根据中间的输出信息判断

网卡名称需要根据实际情况填写

速度问题和太多因素相关了，如果有使用某些TCP加速可能需要关掉
