### ISSUE TITLE
连接一段时间后无法上网，无法重连

### ISSUE THREAD

**Issue by SpadeLushen** [quericy/one-key-ikev2-vpn#90]
Win10系统，在VPN属性里开启了在远程网络上使用默认网关。
一开始能正常连接，大约用了半个小时左右，忽然无法上网，但是VPN连接没有断开。
手动断开重连，显示“无法建立计算机与VPN服务器之间的网络连接，因为远程服务器未响应……”。
此时在服务器上看ipsec status，显示1 up, 0 connecting。运行ipsec restart后依然无法重连，重启服务器也是。
但是过半个小时左右再试，又可以连上正常使用了……
想知道问题出在哪，如何解决

**Comment by quericy** [comment]
可能和某些干扰有关
