### ISSUE TITLE
请教下 ios10.2.1下 IKEv2类型的vpn连接失败是什么原因？  

### ISSUE THREAD

**Issue by ren2881971** [quericy/one-key-ikev2-vpn#91]
搭建的服务器主机是Ubuntu 16    Linode
目前IPSec 类型的vpn可以正常访问。
但是ikev2不可以，点击连接后 失败。
请教是什么原因，又遇到相同问题的童鞋 也可以留言讨论下。

**Comment by ren2881971** [comment]
LZ 自己解决了。。 
造福后人 说下产生问题的原因和解决思路。

**原因：**  
lz没有仔细看**客户端配置说明**的第一条
**连接的服务器地址和证书保持一致,即取决于签发证书ca.cert.pem时使用的是ip还是域名;**

这里 ios中服务器地址和远程id 、签发证书填写的域名 、/usr/local/etc/ipsec.conf 中leftid 都要保持一致，填写域名。（瞎分析难道是不一致 导致证书验证不通过 所以失败的？ 求解释

 [lz的证书是通过acme.sh](https://github.com/Neilpang/acme.sh) 生成的

修改/usr/local/etc/ipsec.conf
```
conn ios_ikev2
    keyexchange=ikev2
    ike=aes256-sha256-modp2048,3des-sha1-modp2048,aes256-sha1-modp2048!
    esp=aes256-sha256,3des-sha1,aes256-sha1!
    rekey=no
    left=%defaultroute
    leftid=“填写域名”
    leftsendcert=always
    leftsubnet=0.0.0.0/0
    leftcert=server.cert.pem
    right=%any
    rightauth=eap-mschapv2
```

请教下怎么查看vpn的连接日志 以及监控流量呢。
最后感谢quericy 膜拜

**Comment by wolaiye1010** [comment]
@ren2881971, 我的也是这个问题，ios ipec 可以连接，ikev2 不能连接。证书是我自己用ache.h  自己签发的。
问题就是 one-key-ikev2-vpn 配置/usr/local/etc/ipsec.conf 里的conn ios_ikev2 ，应该使用我自己签发的域名，而one-key-ikev2-vpn 配置的是ip 所以连接不上，改成域名就可以了，感谢！

**Comment by rockyzhng** [comment]
我看到很多人的配置文件leftid=@xxxx.com, 域名前到底要不要加这个“@”？
