### ISSUE TITLE
centos7，ios10，ikev1，能连接，不能上网

### ISSUE THREAD

**Issue by Liashui** [quericy/one-key-ikev2-vpn#92]
环境：
虚拟机使用桥接模式上网centos7，真机ios10，ikev1

ip：
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:09:61:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.109/24 brd 192.168.1.255 scope global dynamic ens33
       valid_lft 4933sec preferred_lft 4933sec
    inet6 fe80::5aa0:ab11:da56:b4a9/64 scope link 
       valid_lft forever preferred_lft forever

ipsec.conf:
conn android_xauth_psk
    keyexchange=ikev1
    left=%defaultroute
    leftauth=psk
    leftsubnet=0.0.0.0/0
    right=%any
    rightauth=psk
    rightauth2=xauth
    rightsourceip=10.10.10.0/24
    dpdaction=clear
    ikelifetime=500h
    lifetime=200s
    auto=add

iptables：
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [17:1840]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -i ens33 -p udp -m udp --dport 500 -j ACCEPT
-A INPUT -i ens33 -p udp -m udp --dport 4500 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.10.10.0/24 -j ACCEPT

*nat
:PREROUTING ACCEPT [487:73046]
:INPUT ACCEPT [2:940]
:OUTPUT ACCEPT [230:18518]
:POSTROUTING ACCEPT [230:18518]
-A POSTROUTING -s 10.10.10.0/24 -o ens33 -j MASQUERADE

**Comment by Liashui** [comment]
-A FORWARD -s 10.10.10.0/24 -j ACCEPT
-A POSTROUTING -s 10.10.10.0/24 -o ens33 -j MASQUERADE
转发的设置也没有什么问题啊，但是就是连接不上不上网络

**Comment by Liashui** [comment]
@quericy 这个配置有什么问题吗？

**Comment by Liashui** [comment]
也有可能是虚拟机下的ip转发不起作用，所以能连接但是不能访问网络

**Comment by Liashui** [comment]
现在在vultr,直接一键脚本就能通过，没什么问题，建议大家不要在虚拟机上面折腾这个东西，真心费时间，还不好搞定 @quericy  你可以直接关闭这个issue了

**Comment by hellowords** [comment]
@Liashui  您好，我使用作者提供的脚步搭建的vpn服务器，Ubuntu连接接不上vpn，不知道如何配置Ubuntu的客户端，请问能提供思路吗？感谢！

**Comment by Liashui** [comment]
@hellowords 这个脚本是服务器端的吧，你要在ubuntu上面同时运行客户端，服务器？

**Comment by hellowords** [comment]
@Liashui  感谢回复！ 
服务器端的我已经搭建好了，现在客户端是使用ubuntu的，但是连不上VPN，安装strongswan之后不知道如何在客户端配置。

**Comment by Liashui** [comment]
@hellowords 你用mac，windows客户端先测试下服务器是否正常

**Comment by hellowords** [comment]
正常的

**Comment by Liashui** [comment]
@hellowords 我没有配置过ubuntu，不了解，使用场景是啥？路由器里面？
